from pathlib import Path
p=Path('App.tsx')
s=p.read_text()
def r(a,b):
    global s
    if a not in s: raise SystemExit('missing target: '+a[:80])
    s=s.replace(a,b,1)

r("import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';",
  "import { Alert, BackHandler, Image, Modal, Platform, Pressable, SafeAreaView, ScrollView, StatusBar as NativeStatusBar, StyleSheet, Text, View } from 'react-native';")
r("const SESSION_KEY='kubra-hair-atelier:session:v1';","const SESSION_KEY='kubra-hair-atelier:session:v1.1';")
r("const C={bg:'#F5EEE6',paper:'#FFFDF9',ink:'#2D2927',muted:'#817670',line:'#E5D9CF',taupe:'#B69A88',dark:'#3A3432',rose:'#A96562',cream:'#F9F3EC',soft:'#F1E7E3'};",
  "const C={bg:'#F5EFE7',paper:'#FFFCF7',ink:'#352722',muted:'#87756B',line:'#E8DDD2',taupe:'#B99E8C',dark:'#4A3128',rose:'#AE7A6E',cream:'#F9F3EC',soft:'#F2E6DF',champagne:'#D6C1AE'};")
r("function Header({screen,onBack,onSaved}:{screen:Screen;onBack:()=>void;onSaved:()=>void}){return <View style={s.header}>\n<Pressable onPress={onBack} disabled={screen==='home'} style={s.headerSide}><Text style={s.headerIcon}>{screen==='home'?'☰':'‹'}</Text></Pressable>\n<View style={{alignItems:'center'}}><Text style={s.brand}>Kübra Hair Atelier</Text><Text style={s.brandSub}>COLOR INSPIRES YOU</Text></View>\n<Pressable onPress={onSaved} style={s.headerSide}><Text style={s.headerIcon}>♡</Text></Pressable></View>}",
  "function Header({screen,onBack,onSaved}:{screen:Screen;onBack:()=>void;onSaved:()=>void}){return <View style={s.header}>\n<Pressable onPress={onBack} disabled={screen==='home'} style={[s.headerSide,screen==='home'&&{opacity:0}]}><Text style={s.headerIcon}>‹</Text></Pressable>\n<View style={s.brandWrap}><Text style={s.brand}>KÜBRA</Text><Text style={s.brandSub}>HAIR ATELIER</Text></View>\n<Pressable onPress={onSaved} style={s.headerSide}><Text style={s.headerIcon}>♡</Text></Pressable></View>}")
r(" const [comparePreviews,setComparePreviews]=useState<Record<string,string>>({});",
  " const [comparePreviews,setComparePreviews]=useState<Record<string,string>>({});\n const [showExit,setShowExit]=useState(false);\n const [showSplash,setShowSplash]=useState(true);")
r(" useEffect(()=>{if(hydrated)AsyncStorage.setItem(LIBRARY_KEY,JSON.stringify(library)).catch(()=>{})},[library,hydrated]);",
  " useEffect(()=>{if(hydrated)AsyncStorage.setItem(LIBRARY_KEY,JSON.stringify(library)).catch(()=>{})},[library,hydrated]);\n useEffect(()=>{const t=setTimeout(()=>setShowSplash(false),1150);return()=>clearTimeout(t)},[]);\n useEffect(()=>{if(Platform.OS!=='android')return;const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(showExit){setShowExit(false);return true}const p=prev[screen];if(p){setScreen(p);return true}setShowExit(true);return true});return()=>sub.remove()},[screen,showExit]);")
r(" return <SafeAreaView style={s.safe}><StatusBar style=\"dark\"/><Header screen={screen} onBack={back} onSaved={()=>setScreen('saved')}/><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>",
  " if(showSplash)return <View style={s.splash}><StatusBar style=\"dark\"/><View style={s.splashArt}><View style={s.splashRingA}/><View style={s.splashRingB}/><Text style={s.splashWave}>〰</Text></View><View style={s.splashBrand}><Text style={s.splashKubra}>KÜBRA</Text><Text style={s.splashAtelier}>HAIR ATELIER</Text></View><Text style={s.splashTag}>BEAUTY LIVES IN YOUR SHADE</Text></View>;\n return <SafeAreaView style={s.safe}><StatusBar style=\"dark\"/><View style={s.androidInset}/><Header screen={screen} onBack={back} onSaved={()=>setScreen('saved')}/><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>")
r(" {screen==='family'&&<><Title title=\"Choose a color family\" sub={state.photoUri?'Your current photo is already attached and will stay selected.':'Pick a mood. You can always change this later.'} right=\"Reset\" onRight={resetSession}/><View style={s.grid}>{families.map(f=><Pressable key={f.id} onPress={()=>chooseFamily(f.id)} style={s.tile}><Swatch hex={f.color} selected={state.family===f.id}/><Text style={s.tileLabel}>{f.label}</Text></Pressable>)}</View><Button label=\"Next →\" disabled={!state.family} onPress={()=>setScreen('shade')}/></>}",
  " {screen==='family'&&<><Title title=\"Choose a color family\" sub={state.photoUri?'Your photo stays attached while you explore.':'Start broad. You can refine the exact shade next.'} right=\"Reset\" onRight={resetSession}/><View style={s.familyGrid}>{families.map(f=>{const sel=state.family===f.id;return <Pressable key={f.id} onPress={()=>chooseFamily(f.id)} style={s.familyTile}><View style={[s.familySwatch,{backgroundColor:f.color},sel&&s.familySwatchSelected]}><Text style={s.familyTexture}>〰</Text>{sel&&<View style={s.checkBadge}><Text style={s.checkText}>✓</Text></View>}</View><Text style={[s.tileLabel,sel&&s.tileLabelSelected]}>{f.label}</Text></Pressable>})}</View><View style={s.stickyAction}><Button label=\"Next →\" disabled={!state.family} onPress={()=>setScreen('shade')}/></View></>}")
r(" {screen==='shade'&&<><Title title={`${family?.label??'Selected'} shades`} sub=\"Tap a shade to select it. Use ♡ to save it or Compare to add it to the tray.\" right={compare.length?`Compare (${compare.length})`:'Compare'} onRight={()=>setScreen('compare')}/>{familyShades.length?<View style={s.shadeList}>{familyShades.map(x=>{const sel=state.shadeId===x.id;const fav=library.favoriteShadeIds.includes(x.id);const cmp=library.compareShadeIds.includes(x.id);return <Pressable key={x.id} onPress={()=>chooseShade(x.id)} style={[s.shadeCard,sel&&s.shadeCardSelected]}><Swatch hex={x.hex} selected={sel}/><View style={s.shadeInfo}><Text style={s.cardTitle}>{x.name}</Text><Text style={s.meta}>Level {x.level} • {x.tone} • {x.saturation}</Text><View style={s.inlineActions}><Pressable onPress={()=>toggleFavorite(x.id)}><Text style={s.actionLink}>{fav?'♥ Saved':'♡ Save'}</Text></Pressable><Pressable onPress={()=>toggleCompare(x.id)}><Text style={s.actionLink}>{cmp?'✓ Comparing':'+ Compare'}</Text></Pressable></View></View></Pressable>})}</View>:<View style={s.empty}><Text style={s.cardTitle}>No shades found</Text><Text style={s.meta}>Choose another color family.</Text></View>}<Button label=\"Continue →\" disabled={!shade} onPress={()=>setScreen('photo')}/></>}",
  " {screen==='shade'&&<><Title title={`${family?.label??'Selected'} shades`} sub=\"Choose the shade that feels closest to your target.\" right={compare.length?`Compare ${compare.length}`:'Compare'} onRight={()=>setScreen('compare')}/>{familyShades.length?<View style={s.shadeGrid}>{familyShades.map(x=>{const sel=state.shadeId===x.id;const fav=library.favoriteShadeIds.includes(x.id);const cmp=library.compareShadeIds.includes(x.id);return <Pressable key={x.id} onPress={()=>chooseShade(x.id)} style={[s.shadeTile,sel&&s.shadeTileSelected]}><View style={[s.shadeVisual,{backgroundColor:x.hex}]}><Text style={s.shadeTexture}>〰</Text><Pressable onPress={()=>toggleFavorite(x.id)} style={s.favoriteBubble}><Text style={s.favoriteBubbleText}>{fav?'♥':'♡'}</Text></Pressable>{sel&&<View style={s.checkBadge}><Text style={s.checkText}>✓</Text></View>}</View><Text numberOfLines={2} style={s.shadeName}>{x.name}</Text><Text style={s.shadeMeta}>L{x.level} · {x.tone}</Text><Pressable onPress={()=>toggleCompare(x.id)} style={s.compareChip}><Text style={s.compareChipText}>{cmp?'✓ In compare':'+ Compare'}</Text></Pressable></Pressable>})}</View>:<View style={s.empty}><Text style={s.cardTitle}>No shades found</Text><Text style={s.meta}>Choose another color family.</Text></View>}<View style={s.stickyAction}><Button label=\"Continue →\" disabled={!shade} onPress={()=>setScreen('photo')}/></View></>}")
r(" </ScrollView></SafeAreaView>\n}",
  " </ScrollView><Modal transparent visible={showExit} animationType=\"fade\" onRequestClose={()=>setShowExit(false)}><View style={s.modalBackdrop}><View style={s.exitCard}><View style={s.exitMark}><Text style={s.exitMarkText}>KA</Text></View><Text style={s.exitTitle}>Leave Kübra Hair Atelier?</Text><Text style={s.exitCopy}>Your current look and selections are saved for next time.</Text><View style={s.exitActions}><Pressable onPress={()=>setShowExit(false)} style={s.exitStay}><Text style={s.exitStayText}>Stay</Text></Pressable><Pressable onPress={()=>BackHandler.exitApp()} style={s.exitLeave}><Text style={s.exitLeaveText}>Exit</Text></Pressable></View><Text style={s.exitTag}>BEAUTY LIVES IN YOUR SHADE</Text></View></View></Modal></SafeAreaView>\n}")
r("safe:{flex:1,backgroundColor:C.bg},header:{height:76,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.line,backgroundColor:C.paper},headerSide:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerIcon:{fontSize:25,color:C.ink},brand:{fontFamily:'serif',fontSize:20,color:C.ink},brandSub:{fontSize:8,letterSpacing:3,color:C.muted,marginTop:3},page:{padding:18,paddingBottom:44},",
  "safe:{flex:1,backgroundColor:C.bg},androidInset:{height:Platform.OS==='android'?(NativeStatusBar.currentHeight??0):0,backgroundColor:C.bg},header:{height:72,paddingHorizontal:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:C.bg},headerSide:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},headerIcon:{fontSize:28,color:C.dark},brandWrap:{alignItems:'center',justifyContent:'center'},brand:{fontFamily:'serif',fontWeight:'700',fontSize:22,letterSpacing:4,color:C.ink},brandSub:{fontSize:8,letterSpacing:3.4,color:C.muted,marginTop:2},page:{paddingHorizontal:20,paddingTop:14,paddingBottom:52},")
extra="""
splash:{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center',paddingHorizontal:30},splashArt:{width:250,height:250,alignItems:'center',justifyContent:'center',marginBottom:18},splashRingA:{position:'absolute',width:220,height:220,borderRadius:110,borderWidth:22,borderColor:'#DDC9BA',opacity:.48,transform:[{rotate:'18deg'}]},splashRingB:{position:'absolute',width:170,height:230,borderRadius:100,borderWidth:16,borderColor:'#CDB3A0',opacity:.34,transform:[{rotate:'-26deg'}]},splashWave:{fontFamily:'serif',fontSize:138,color:'#8E776A',opacity:.42,transform:[{rotate:'-18deg'}]},splashBrand:{alignItems:'center'},splashKubra:{fontFamily:'serif',fontWeight:'700',fontSize:34,letterSpacing:7,color:C.ink},splashAtelier:{fontSize:10,letterSpacing:5,color:C.muted,marginTop:5},splashTag:{position:'absolute',bottom:54,fontSize:9,letterSpacing:3.1,color:C.muted},
familyGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:4},familyTile:{width:'31%',minWidth:96,alignItems:'center',marginBottom:8},familySwatch:{width:'100%',aspectRatio:1,borderRadius:22,overflow:'hidden',justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:'rgba(70,45,35,.08)'},familySwatchSelected:{borderWidth:2,borderColor:C.dark,transform:[{scale:.98}]},familyTexture:{fontFamily:'serif',fontSize:86,color:'#FFF',opacity:.18,transform:[{rotate:'-18deg'}]},checkBadge:{position:'absolute',right:8,top:8,width:27,height:27,borderRadius:14,backgroundColor:C.paper,alignItems:'center',justifyContent:'center',shadowColor:'#000',shadowOpacity:.1,shadowRadius:5,elevation:2},checkText:{fontSize:14,color:C.dark,fontWeight:'700'},tileLabelSelected:{fontWeight:'700'},stickyAction:{marginTop:14},
shadeGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},shadeTile:{width:'48%',backgroundColor:C.paper,borderRadius:24,padding:9,borderWidth:1,borderColor:C.line},shadeTileSelected:{borderWidth:2,borderColor:C.dark},shadeVisual:{width:'100%',aspectRatio:.92,borderRadius:18,alignItems:'center',justifyContent:'center',overflow:'hidden'},shadeTexture:{fontFamily:'serif',fontSize:108,color:'#FFF',opacity:.17,transform:[{rotate:'-20deg'}]},favoriteBubble:{position:'absolute',left:8,top:8,width:32,height:32,borderRadius:16,backgroundColor:'rgba(255,252,247,.9)',alignItems:'center',justifyContent:'center'},favoriteBubbleText:{color:C.dark,fontSize:17},shadeName:{fontFamily:'serif',fontSize:17,lineHeight:20,color:C.ink,marginTop:10,minHeight:40},shadeMeta:{fontSize:10,color:C.muted,marginTop:2},compareChip:{alignSelf:'flex-start',paddingVertical:7,paddingHorizontal:10,borderRadius:999,backgroundColor:C.cream,marginTop:9},compareChipText:{fontSize:10,color:C.dark},
modalBackdrop:{flex:1,backgroundColor:'rgba(48,34,29,.38)',alignItems:'center',justifyContent:'center',padding:28},exitCard:{width:'100%',maxWidth:360,backgroundColor:C.paper,borderRadius:30,padding:24,alignItems:'center',shadowColor:'#000',shadowOpacity:.18,shadowRadius:20,elevation:8},exitMark:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:C.champagne,alignItems:'center',justifyContent:'center',marginBottom:16},exitMarkText:{fontFamily:'serif',fontSize:14,color:C.dark},exitTitle:{fontFamily:'serif',fontSize:27,textAlign:'center',color:C.ink},exitCopy:{fontSize:13,lineHeight:20,textAlign:'center',color:C.muted,marginTop:9,marginBottom:18},exitActions:{width:'100%',flexDirection:'row',gap:10},exitStay:{flex:1,minHeight:52,borderRadius:18,borderWidth:1,borderColor:C.taupe,alignItems:'center',justifyContent:'center'},exitLeave:{flex:1,minHeight:52,borderRadius:18,backgroundColor:C.dark,alignItems:'center',justifyContent:'center'},exitStayText:{color:C.dark,fontWeight:'600'},exitLeaveText:{color:'#FFF',fontWeight:'600'},exitTag:{fontSize:8,letterSpacing:2.3,color:C.muted,marginTop:18},
"""
r("const s=StyleSheet.create({\n", "const s=StyleSheet.create({\n"+extra)
p.write_text(s)

import json
for name in ('package.json','app.json'):
    q=Path(name); d=json.loads(q.read_text())
    if name=='package.json': d['version']='1.1.0'
    else:
        d['expo']['version']='1.1.0'; d['expo']['android']['versionCode']=2; d['expo']['ios']['buildNumber']='2'
    q.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print('v1.1 patch applied')
